version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    circleci_ip_ranges: true
    macos:
      xcode: 12.2.0 # version of Xcode
    steps:
      - checkout  # pull down code from
      - run:
          name: Run Unit Tests  # xcode's 'swift test' doesn't yet allow specifying iOS only, and this package does not work on macOS, so all we do here for the time being is build the app to check it at least can compile.  
          command: |-
            for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
            brew install sonar-scanner
            swift test --enable-code-coverage
            xcrun llvm-cov show .build/debug/w3w-swift-componentsPackageTests.xctest/Contents/MacOS/w3w-swift-componentsPackageTests  -instr-profile .build/debug/codecov/default.profdata > .build/cov.txt
            sonar-scanner -Dsonar.projectKey=what3words_w3w-swift-components -Dsonar.organization=what3words -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN -Dsonar.sources=Sources -Dsonar.swift.coverage.reportPath=.build/cov.txt
            #xcodebuild -scheme w3w-swift-components -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
            #xcodebuild -scheme w3w-swift-components test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
          
workflows:
  version: 2
  test_build:
    jobs:
      - test
